----------------- AIRPLANES -----------------

CREATE TABLE "ATTGRP1 "."AIRPLANES"  (
		  "AIRCRAFT_REGISTRATION" CHAR(7 OCTETS) NOT NULL , 
		  "MODEL" VARCHAR(25 OCTETS) NOT NULL , 
		  "SEATS_BUSINESS" SMALLINT , 
		  "SEATS_PREMIUM" SMALLINT , 
		  "SEATS_ECONOMY" SMALLINT , 
		  "CREW_MEMBERS" SMALLINT , 
		  "BUILD_DATE" DATE NOT NULL , 
		  "FUEL_GALLONS_HOUR" SMALLINT NOT NULL , 
		  "MAINTENANCE_LAST_ACHECK" DATE NOT NULL , 
		  "MAINTENANCE_LAST_BCHECK" DATE NOT NULL , 
		  "MAINTENANCE_TAKEOFFS" SMALLINT NOT NULL , 
		  "MAINTENANCE_FLIGHT_HOURS" INTEGER NOT NULL , 
		  "TOTAL_FLIGHT_DISTANCE" INTEGER NOT NULL )   
		 COMPRESS YES ADAPTIVE  
		 IN "TBSPACE1"  
		 ORGANIZE BY ROW;

ALTER TABLE "ATTGRP1 "."AIRPLANES" 
	ADD PRIMARY KEY
		("AIRCRAFT_REGISTRATION")
	ENFORCED;

GRANT CONTROL ON TABLE "ATTGRP1 "."AIRPLANES" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL260604145118130" TO USER "ATTGRP1 ";




----------------- AIRPORTS -----------------


CREATE TABLE "ATTGRP1 "."AIRPORTS"  (
		  "IATA_CODE" CHAR(3 OCTETS) NOT NULL , 
		  "AIRPORT" VARCHAR(50 OCTETS) NOT NULL , 
		  "CITY" VARCHAR(20 OCTETS) NOT NULL , 
		  "COUNTRY" VARCHAR(20 OCTETS) NOT NULL , 
		  "CONTINENT" VARCHAR(20 OCTETS) NOT NULL , 
		  "TIMEZONE" VARCHAR(6 OCTETS) NOT NULL , 
		  "LATITUDE" DOUBLE NOT NULL , 
		  "LONGITUDE" DOUBLE NOT NULL , 
		  "AIRPORT_TAX" DECIMAL(5,2) )   
		 COMPRESS YES ADAPTIVE  
		 IN "TBSPACE1"  
		 ORGANIZE BY ROW;

ALTER TABLE "ATTGRP1 "."AIRPORTS" 
	ADD PRIMARY KEY
		("IATA_CODE")
	ENFORCED;

GRANT CONTROL ON TABLE "ATTGRP1 "."AIRPORTS" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL260604145449560" TO USER "ATTGRP1 ";





----------------- FLIGHTS -----------------


CREATE TABLE "ATTGRP1 "."FLIGHTS"  (
		  "FLIGHT_ID" CHAR(6 OCTETS) NOT NULL , 
		  "FLIGHT_LEG" SMALLINT NOT NULL , 
		  "FREQUENCY" CHAR(2 OCTETS) NOT NULL , 
		  "ROUTE_CODE" CHAR(4 OCTETS) NOT NULL , 
		  "DEPARTURE" TIMESTAMP(0) NOT NULL , 
		  "ARRIVAL" TIMESTAMP(0) NOT NULL , 
		  "AIRPLANE" CHAR(7 OCTETS) NOT NULL , 
		  "PRICE_ECONOMY" DECIMAL(6,2) , 
		  "PRICE_PREMIUM" DECIMAL(6,2) , 
		  "PRICE_BUSINESS" DECIMAL(6,2) )   
		 COMPRESS YES ADAPTIVE  
		 PARTITION BY RANGE("DEPARTURE") 
		 (PART "P2010" STARTING('2010-01-01-00.00.00') ENDING('2010-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2011" STARTING('2011-01-01-00.00.00') ENDING('2011-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2012" STARTING('2012-01-01-00.00.00') ENDING('2012-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2013" STARTING('2013-01-01-00.00.00') ENDING('2013-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2014" STARTING('2014-01-01-00.00.00') ENDING('2014-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2015" STARTING('2015-01-01-00.00.00') ENDING('2015-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2016" STARTING('2016-01-01-00.00.00') ENDING('2016-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2017" STARTING('2017-01-01-00.00.00') ENDING('2017-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2018" STARTING('2018-01-01-00.00.00') ENDING('2018-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2019" STARTING('2019-01-01-00.00.00') ENDING('2019-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2020" STARTING('2020-01-01-00.00.00') ENDING('2020-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2021" STARTING('2021-01-01-00.00.00') ENDING('2021-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2022" STARTING('2022-01-01-00.00.00') ENDING('2022-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2023" STARTING('2023-01-01-00.00.00') ENDING('2023-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2024" STARTING('2024-01-01-00.00.00') ENDING('2024-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2025" STARTING('2025-01-01-00.00.00') ENDING('2025-12-31-23.59.59') IN "TBSPACE1", 
		 PART "P2026" STARTING('2026-01-01-00.00.00') ENDING('2026-12-31-23.59.59') IN "TBSPACE1") 
		 ORGANIZE BY ROW;

CREATE UNIQUE INDEX "ATTGRP1 "."IX_FLIGHTS_00" ON "ATTGRP1 "."FLIGHTS" 
		("FLIGHT_ID" ASC,
		 "FLIGHT_LEG" ASC,
		 "DEPARTURE" ASC)
		PARTITIONED
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "ATTGRP1 "."IX_FLIGHTS_01" ON "ATTGRP1 "."FLIGHTS" 
		("ROUTE_CODE" ASC)
		PARTITIONED
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "ATTGRP1 "."IX_FLIGHTS_02" ON "ATTGRP1 "."FLIGHTS" 
		("AIRPLANE" ASC)
		PARTITIONED
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

ALTER TABLE "ATTGRP1 "."FLIGHTS" 
	ADD PRIMARY KEY
		("FLIGHT_ID",
		 "ROUTE_CODE",
		 "DEPARTURE")
	ENFORCED;

ALTER TABLE "ATTGRP1 "."FLIGHTS" 
	ADD CONSTRAINT "FK_FLIGHTS_01" FOREIGN KEY
		("ROUTE_CODE")
	REFERENCES "ATTGRP1 "."ROUTES"
		("ROUTE_CODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "ATTGRP1 "."FLIGHTS" 
	ADD CONSTRAINT "FK_FLIGHTS_02" FOREIGN KEY
		("AIRPLANE")
	REFERENCES "ATTGRP1 "."AIRPLANES"
		("AIRCRAFT_REGISTRATION")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

GRANT CONTROL ON TABLE "ATTGRP1 "."FLIGHTS" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "ATTGRP1 "."IX_FLIGHTS_00" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "ATTGRP1 "."IX_FLIGHTS_01" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "ATTGRP1 "."IX_FLIGHTS_02" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL260604145622760" TO USER "ATTGRP1 ";






----------------- ROUTES -----------------

CREATE TABLE "ATTGRP1 "."ROUTES"  (
		  "ROUTE_CODE" CHAR(4 OCTETS) NOT NULL , 
		  "ORIGIN" CHAR(3 OCTETS) NOT NULL , 
		  "DESTINATION" CHAR(3 OCTETS) NOT NULL , 
		  "PARENT_ROUTE" CHAR(6 OCTETS) NOT NULL , 
		  "LEG_NUMBER" SMALLINT NOT NULL , 
		  "DISTANCE" INTEGER , 
		  "FLIGHT_MINUTES" SMALLINT )   
		 COMPRESS YES ADAPTIVE  
		 IN "TBSPACE1"  
		 ORGANIZE BY ROW;

CREATE INDEX "ATTGRP1 "."IX_ROUTES_01" ON "ATTGRP1 "."ROUTES" 
		("ORIGIN" ASC)
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

CREATE INDEX "ATTGRP1 "."IX_ROUTES_02" ON "ATTGRP1 "."ROUTES" 
		("DESTINATION" ASC)
		
		COMPRESS YES 
		INCLUDE NULL KEYS ALLOW REVERSE SCANS;

ALTER TABLE "ATTGRP1 "."ROUTES" 
	ADD PRIMARY KEY
		("ROUTE_CODE")
	ENFORCED;

ALTER TABLE "ATTGRP1 "."ROUTES" 
	ADD CONSTRAINT "FK_ROUTE_01" FOREIGN KEY
		("ORIGIN")
	REFERENCES "ATTGRP1 "."AIRPORTS"
		("IATA_CODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "ATTGRP1 "."ROUTES" 
	ADD CONSTRAINT "FK_ROUTE_02" FOREIGN KEY
		("DESTINATION")
	REFERENCES "ATTGRP1 "."AIRPORTS"
		("IATA_CODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "ATTGRP1 "."ROUTES" 
	ADD CONSTRAINT "FK_ROUTE_03" FOREIGN KEY
		("PARENT_ROUTE")
	REFERENCES "ATTGRP1 "."ROUTES"
		("ROUTE_CODE")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

GRANT CONTROL ON TABLE "ATTGRP1 "."ROUTES" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "ATTGRP1 "."IX_ROUTES_01" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "ATTGRP1 "."IX_ROUTES_02" TO USER "ATTGRP1 ";

GRANT CONTROL ON INDEX "SYSIBM  "."SQL260604145454340" TO USER "ATTGRP1 ";




----------------- FLIGHT_CREW  -----------------


CREATE TABLE public."FLIGHT_CREW" (
	"EMPNO" int4 NOT NULL,
	"FLIGHT_ID" bpchar(6) NOT NULL,
	"ROUTE_CODE" bpchar(4) NOT NULL,
	"DEPARTURE" timestamp(0) NOT NULL,
	CONSTRAINT "FLIGHT_CREW_pkey" PRIMARY KEY ("EMPNO", "FLIGHT_ID", "ROUTE_CODE", "DEPARTURE")
);


----------------- STAFF  -----------------

CREATE TABLE `STAFF` (
  `EMPNO` int NOT NULL,
  `FIRSTNME` varchar(20) NOT NULL,
  `MIDINIT` char(1) DEFAULT NULL,
  `LASTNAME` varchar(20) NOT NULL,
  `GENDER` char(1) DEFAULT NULL,
  `PASSPORT` varchar(12) NOT NULL,
  `BIRTHDATE` date NOT NULL,
  `HIREDATE` date NOT NULL,
  `DIVISION` varchar(40) NOT NULL,
  `DEPARTMENT` varchar(40) NOT NULL,
  `MARITAL_STATUS` varchar(40) NOT NULL,
  `PHONE` char(9) DEFAULT NULL,
  `EMAIL` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`EMPNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;