

--- Number of staff
SELECT 
	DEPARTMENT,
	COUNT(DISTINCT EMPNO) 
FROM STAFF
GROUP BY 
	DEPARTMENT


--- avg km and time per staff memember 
SELECT 
	fc.EMPNO,
	fc.FLIGHT_ID,
	fc.ROUTE_CODE,
	fc.DEPARTURE,
	r.distance,
	r.minutes 
FROM FLIGHT_CREW AS fc
LEFT JOIN ROUTE AS r ON fc.ROUTE_CODE = r.ROUTE_CODE
LEFT JOIN STAFF AS s ON fc.EMPNO = s.EMPNO
GROUP BY 
	FLIGHT_ID,
	ROUTE_CODE,
	DEPARTURE


--- staff usage

WITH fc as (
SELECT 	
	fc.FLIGHT_ID,
	fc.ROUTE_CODE,
	fc.DEPARTURE,
	COUNT(DISTINCT fc.EMPNO) as USED_CREW
FROM FLIGHT_CREW AS fc
GROUP BY 
	FLIGHT_ID,
	ROUTE_CODE,
	DEPARTURE
)

SELECT 
	f.FLIGHT_ID,
	f.ROUTE_CODE,
	f.DEPARTURE,
	f.AIRPLANE,
	a.CREW_MEMBERS AS REQUIRED_CREW,
	a.MODEL AS AIRPLANE_MODEL,
	a.AIRCRAFT_REGISTRATION AS AIRPLANE,
	fc.USED_CREW
FROM FLIGHTS AS f 
LEFT JOIN AIRPLANES AS a ON f.AIRPLANE = a.AIRCRAFT_REGISTRATION
LEFT JOIN fc ON 
	fc.FLIGHT_ID = f.FLIGHT_ID AND
	fc.ROUTE_CODE = f.ROUTE_CODE AND
	fc.DEPARTURE = f.DEPARTURE



